embeddings:
  provider: "nvidia"
  api_key: "YOUR_SUPER_SECRET_NVIDIA_API_KEY"
  model: "nv-embedqa-mistral-7b-v2"
llm:
  provider: "nvidia"
  api_key: "YOUR_SUPER_SECRET_NVIDIA_API_KEY"
  model: "nvidia/nemotron-4-340b-instruct"
  temperature: 0
  max_tokens: 8192