embeddings:
  provider: "groq"
  api_key: "YPUR_SUPER_SECRET_GROQ_API_KEY"
  model: "nomic-embed-text-v1_5"
llm:
  provider: "groq"
  api_key: "YPUR_SUPER_SECRET_GROQ_API_KEY"
  model: "deepseek-r1-distill-llama-70b"
  temperature: 0
  max_tokens: 8192