embeddings:
  provider: "mistral"
  api_key: "YPUR_SUPER_SECRET_MISTRAL_API_KEY"
  model: "mistral-embed"
llm:
  provider: "mistral"
  api_key: "YPUR_SUPER_SECRET_MISTRAL_API_KEY"
  model: "mistral-large-latest"
  temperature: 0
  max_tokens: 8192